<?php
/** @var \Illuminate\Database\Eloquent\Factory $factory */
$factory->define(Crashplan_model::class, function (Faker\Generator $faker) {

    return [
        'app_log_time' => $faker->dateTimeBetween('-4 months', 'now'),
        'app_log_locale' => $faker->randomElement(['English (United States), America/New_York']),
        'cp_version' => $faker->randomElement(['8.5.0 - 1525200006820 - Build: 1054', '8.4.0 - 1525200002860 - Build: 1043']),
        'org_type' => $faker->randomElement(['ENTERPRISE', 'PERSONAL'),
        'license_authorized' => $faker->boolean(),
        'auth_rules' => $faker->randomElement(['safe', 'unsafe', 'tacos']),
        'license_model' => $faker->randomElement(['info', 'debug', 'verbose', 'silent']),
        'license_features' => $faker->randomElement(['Production', 'Development']),
        'last_connected' => $faker->dateTimeBetween('-4 months', 'now'),
        'backup_enabled' => $faker->boolean(),
        'backup_paths' => $faker->randomElement(['/Users/Shared/Tux, /Users/Shared/Flammable', '/Users/Shared/Bochoven']),
        'backup_paths_last_modified' => $faker->dateTimeBetween('-4 months', 'now'),
        'backup_scanning' => $faker->boolean(),
        'backup_check_for_deletes' => $faker->boolean(),
        'backup_total_files' => $faker->numberBetween(70000, 100000),
        'backup_total_size' => $faker->randomElement(['991.7MB', '2.7TB', '7.1GB']),
        'backup_frequency' => $faker->randomElement(['25min 0sec', '45min 0sec', '10min 0sec']),
        'backup_open_files' => $faker->boolean(),
        'backup_scan_interval' => $faker->randomElement(['7day 0hr', '1day 0hr', '3day 6hr']),
        'backup_scan_time' => $faker->dateTimeBetween('-4 months', 'now'),
        'backup_compression' => $faker->boolean(),
        'backup_encryption' => $faker->boolean(),
        'backup_data_deduplication' => $faker->randomElement(['FULL', 'PARTIAL', 'NONE']),
        'backup_keep_deleted' => $faker->boolean(),
        'backup_keep_deleted_minutes' => $faker->randomElement(['4hr', '1hr', '8hr']),
        'backup_version_last_week' => $faker->randomElement(['10min 0sec', '2min 0sec', '45min 0sec']),
        'backup_version_ninety_days' => $faker->randomElement(['1day 0hr', '3day 0hr', '7day 0hr']),
        'backup_version_year' => $faker->randomElement(['99day 0hr', '30day 0hr', '7day 0hr']),
        'backup_version_previous_year' => $faker->randomElement(['365day 0hr', '48day 0hr', '24day 0hr']),
        'app_log_size' => $faker->numberBetween(70000, 100000),
        'backup_start_time' => $faker->dateTimeBetween('-4 months', 'now'),
        'backup_destination' => $faker->randomElement(['Code42 Cloud', 'Code42 Ocean', 'Grandmas Shoebox']),
        'backup_start_files' => $faker->randomElement(['100 files (9.90MB)', '130 files (84.90MB)', '10 files (2.97MB)']),
        'backup_complete_time' => $faker->dateTimeBetween('-4 months', 'now'),
        'backup_time' => $faker->dateTimeBetween('-4 months', 'now'),
        'backup_end_files' => $faker->randomElement(['100 files (9.90MB)', '130 files (84.90MB)', '10 files (2.97MB)']),
        'backup_sent' => $faker->randomElement(['9.90MB', '84.90MB', '2.97MB']),
        'backup_sent_speed' => $faker->randomElement(['324.7Kbps (Effective rate: 6.1Mbps)'),
        'cp_guid_change_time' => $faker->dateTimeBetween('-4 months', 'now'),
        'cp_guid_old' => $faker->numberBetween(70000000, 100000000),
        'cp_guid_new' => $faker->numberBetween(70000000, 100000000),
        'history_log_size' => $faker->numberBetween(70000, 100000),
        'auth_date' => $faker->dateTimeBetween('-4 months', 'now'),
        'org_name' => $faker->randomElement(['Tuxuco', 'Bochoven Co.'),
        'guid' => $faker->numberBetween(70000000, 100000000),
        'cp_username' => $faker->randomElement(['tux@munkireport.null', 'bochoven@munkireport.null'),
    ];
});
